#if !defined(INCLUDED_SLEPCCONF_H)
#define INCLUDED_SLEPCCONF_H

#define SLEPC_PETSC_DIR "D:/work_station/hpcCode/petsc-3.22.4"
#define SLEPC_PETSC_ARCH "arch-mswin-c-opt"
#define SLEPC_DIR "D:/work_station/hpcCode/slepc-3.22.2"
#define SLEPC_LIB_DIR "D:/work_station/installedCode/slepc/lib"
#define SLEPC_MISSING_LAPACK_LAEV2 1
#define SLEPC_MISSING_LAPACK_GEHRD 1
#define SLEPC_MISSING_LAPACK_LANHS 1
#define SLEPC_MISSING_LAPACK_TREXC 1
#define SLEPC_MISSING_LAPACK_TREVC 1
#define SLEPC_MISSING_LAPACK_TGEXC 1
#define SLEPC_MISSING_LAPACK_TGEVC 1
#define SLEPC_MISSING_LAPACK_STEDC 1
#define SLEPC_MISSING_LAPACK_HSEIN 1
#define SLEPC_MISSING_LAPACK_LARFG 1
#define SLEPC_MISSING_LAPACK_LARF 1
#define SLEPC_MISSING_LAPACK_LASCL 1
#define SLEPC_MISSING_LAPACK_TRSYL 1
#define SLEPC_MISSING_LAPACK_BDSQR 1
#define SLEPC_MISSING_LAPACK_GEBRD 1
#define SLEPC_MISSING_LAPACK_ORGHR 1
#define SLEPC_MISSING_LAPACK_SYTRD 1
#define SLEPC_MISSING_LAPACK_ORGTR 1
#define SLEPC_MISSING_LAPACK_ORMBR 1
#define SLEPC_MISSING_LAPACK_STEVR 1
#define SLEPC_MISSING_LAPACK_BDSDC 1
#define SLEPC_MISSING_LAPACK_LAG2 1
#define SLEPC_MISSING_LAPACK_LASV2 1
#define SLEPC_MISSING_LAPACK_LARTG 1
#define SLEPC_MISSING_LAPACK_LAED4 1
#define SLEPC_MISSING_LAPACK_LAMRG 1
#define SLEPC_MISSING_LAPACK_GGSVD3 1
#define SLEPC_MISSING_LAPACK_GGSVD 1
#define SLEPC_MISSING_LAPACK_GGEV3 1
#define SLEPC_MISSING_LAPACK_GGEV 1
#define SLEPC_MISSING_LAPACK_GGES3 1
#define SLEPC_HAVE_PACKAGES ":"
#endif
